---
global:
  provider: aws
  env: dev
  network: mainnet
  elc: besu
  clc: teku
  snapshot:
    # sot (source of truth) node, ie this is what we will create snapshots of
    sot: true
    # use the defaults of hourly, daily, weekly
    schedule: "@hourly"

elc:
  image:
    elc:
      repository: hyperledger/besu
      tag: latest
  restore:
    enabled: false
    snapshot: ""
  storage:
    allowVolumeExpansion: true
    volumeBindingMode: WaitForFirstConsumer
    reclaimPolicy: Delete
    size: "1000Gi"
    parameters:
      type: gp3
      csi.storage.k8s.io/fstype: xfs
  tolerations:
    - key: ethereum
      value: "true"
      effect: NoExecute
    - key: ethereum
      value: "true"
      effect: NoSchedule      
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              workloadType: ethereum
          topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: workloadType
            operator: In
            values:
            - ethereum
clc:
  image:
    clc:
      repository: consensys/teku
      tag: latest
  restore:
    enabled: false
    snapshot: ""
  storage:
    allowVolumeExpansion: true
    volumeBindingMode: WaitForFirstConsumer
    reclaimPolicy: Delete
    size: "250Gi"
    parameters:
      type: gp3
      csi.storage.k8s.io/fstype: xfs
  tolerations:
    - key: ethereum
      value: "true"
      effect: NoExecute
    - key: ethereum
      value: "true"
      effect: NoSchedule
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              workloadType: ethereum
          topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: workloadType
            operator: In
            values:
            - ethereum      