{{ if eq .Values.global.elc "besu" -}}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ethnode-elc.fullname" . }}-{{ .Values.global.network }}-{{ .Values.global.env }}
  labels:
    {{- include "ethnode-elc.labels" . | nindent 4 }}
  namespace: {{ include "ethnode.namespace" . }}
spec:
  replicas: 1
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "ethnode-elc.labels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.global.elc }}
  serviceName: {{ include "ethnode-elc.fullname" . }}-{{ .Values.global.network }}-{{ .Values.global.env }}
  template:
    metadata:
      labels:
        {{- include "ethnode-elc.labels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.global.elc }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.settings.metrics.port | quote}}
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: {{ include "ethnode-elc.fullname" . }}-{{ .Values.global.network }}-{{ .Values.global.env }}
      automountServiceAccountToken: {{ .Values.serviceAccount.autoMount }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- if or .Values.image.pullSecrets .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- include "ethnode-elc.imagePullSecrets" . | nindent 8 }}
      {{- end }}

      initContainers:
      - name: init
        image: {{ .Values.image.hooks.repository }}:{{ .Values.image.hooks.tag }}
        volumeMounts:
          - name: elc-pip
            mountPath: /pip
          - name: elc-data
            mountPath: {{ .Values.settings.dataPath }}
        securityContext:
          runAsUser: 0                        
        command:
        - /bin/bash
        - -xec
        - |
          # get the existing public ip to associate with
          PUBLIC_IP_TO_ASSOCIATE=$(curl ifconfig.io)
          echo "PUBLIC_IP_TO_ASSOCIATE: $PUBLIC_IP_TO_ASSOCIATE"
          echo -ne "$PUBLIC_IP_TO_ASSOCIATE" > /pip/ip
          
          # update permissions on the data volume
          chown -R 1000:1000 {{ .Values.settings.dataPath }}

      containers:
      - name: besu
        image: {{ .Values.image.elc.repository }}:{{ .Values.image.elc.tag }}
        imagePullPolicy: {{ .Values.image.elc.imagePullPolicy }}
        resources:
          requests:
            cpu: "{{ .Values.resources.cpuRequest }}"
            memory: "{{ .Values.resources.memRequest }}"
          limits:
            cpu: "{{ .Values.resources.cpuLimit }}"
            memory: "{{ .Values.resources.memLimit }}"
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          {{- if or (eq .Values.global.provider "aws") (eq .Values.global.provider "azure") }}
          # just makes this easier to read locally          
          - name: LOG4J_CONFIGURATION_FILE
            value: /etc/besu/log4j.xml
          {{- end }}
        volumeMounts:
          - name: elc-pip
            mountPath: /pip
            readOnly: true
          - name: besu-config-toml
            mountPath: /etc/besu
            readOnly: true
          - name: elc-data
            mountPath: {{ .Values.settings.dataPath }}
          - name: elc-jwt
            mountPath: {{ .Values.global.jwt.secretPath }}
            readOnly: true            
        ports:
          - name: elc-rpc
            containerPort: {{ .Values.settings.rpc.port }}
            protocol: TCP
          - name: elc-ws
            containerPort: {{ .Values.settings.ws.port }}
            protocol: TCP
          - name: elc-rlpx
            containerPort: {{ .Values.settings.p2p.port }}
            protocol: TCP
          - name: elc-discovery
            containerPort: {{ .Values.settings.p2p.port }}
            protocol: UDP
          - name: elc-metrics
            containerPort: {{ .Values.settings.metrics.port }}
            protocol: TCP
          - name: elc-engine
            containerPort: {{ .Values.settings.engine.rpcPort }}
            protocol: TCP  
        command:
          - /bin/sh
          - -c
        args:
          - |
            exec

            pip=$(cat /pip/ip)

            /opt/besu/bin/besu \
              --data-path={{ .Values.settings.dataPath | quote }} \
              --network={{ .Values.global.network | quote }} \
              --logging={{ .Values.settings.logging | quote }} \
              --node-private-key-file={{.Values.settings.privateKeyFilePath | quote }} \
              --min-gas-price=1000 \
              --tx-pool-price-bump={{ .Values.settings.txPool.priceBump }} \
              --data-storage-format={{ .Values.settings.dataStorageFormat | quote }} \
              --sync-mode={{ .Values.settings.syncMode | quote }} \
              --Xdns-enabled=true \
              --Xdns-update-enabled=true \
              --nat-method="NONE" \
              --Xsnapsync-synchronizer-flat-db-healing-enabled=true \
              --p2p-enabled=true \
              --p2p-host=${pip} \
              --p2p-port={{ .Values.settings.p2p.port }} \
              --discovery-enabled={{ .Values.settings.p2p.discovery }} \
              --max-peers={{ .Values.settings.p2p.maxPeers }} \
              --engine-jwt-disabled={{ .Values.settings.engine.jwtDisabled }} \
              --engine-jwt-secret="{{ .Values.global.jwt.secretPath }}/jwtSecret.hex" \
              --engine-rpc-enabled={{ .Values.settings.engine.rpcEnabled }} \
              --engine-rpc-port={{ .Values.settings.engine.rpcPort }} \
              --engine-host-allowlist={{ join "," .Values.global.jwt.hostAllowlist }} \
              --host-allowlist={{ join "," .Values.settings.http.allowlist }} \
              --rpc-http-enabled={{ .Values.settings.rpc.enabled }} \
              --rpc-http-host={{ .Values.settings.rpc.host | quote }} \
              --rpc-http-port={{ .Values.settings.rpc.port }} \
              --rpc-http-api={{ join "," .Values.settings.rpc.api }} \
              --rpc-http-cors-origins={{ join "," .Values.settings.rpc.corsOrigins }} \
              --rpc-http-authentication-enabled={{ .Values.settings.rpc.authenticationEnabled }} \
              --revert-reason-enabled=true \
              --rpc-ws-enabled={{ .Values.settings.ws.enabled }} \
              --rpc-ws-host={{ .Values.settings.ws.host | quote }} \
              --rpc-ws-port={{ .Values.settings.ws.port }} \
              --rpc-ws-api={{ join "," .Values.settings.ws.api }} \
              --rpc-ws-authentication-enabled={{ .Values.settings.ws.authenticationEnabled }} \
              --metrics-enabled=true \
              --metrics-host={{ .Values.settings.metrics.host | quote }} \
              --metrics-port={{ .Values.settings.metrics.port }} 

        livenessProbe:
          httpGet:
            path: "/liveness"
            port: {{ .Values.settings.rpc.port }}
            httpHeaders:
              - name:  Content-Type
                value: application/json              
          initialDelaySeconds: 120
          periodSeconds: 30
      
      volumes:
      - name: besu-config-toml
        configMap:
          name: {{ include "ethnode-elc.fullname" . }}-{{ .Values.global.network }}-{{ .Values.global.env }}-config
      - name: elc-jwt
        secret:
          secretName: {{ .Release.Name }}-ethnode-{{ .Values.global.network }}-{{ .Values.global.env }}-jwt         
      - name: elc-pip
        emptyDir: {}
      - name: elc-data
        persistentVolumeClaim:
          claimName: {{ include "ethnode-elc.fullname" . }}-{{ .Values.global.network }}-{{ .Values.global.env }}-pvc

{{- end }}

