{{- if or (eq .Values.global.provider "aws") (eq .Values.global.provider "azure") }}

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "ethnode-clc.fullname" . }}-{{ .Values.global.network }}-{{ .Values.global.env }}-storage
  labels:
    {{- include "ethnode-clc.labels" . | nindent 4 }}  
  namespace: {{ include "ethnode.namespace" . }}
volumeBindingMode: {{ .Values.storage.volumeBindingMode }}
reclaimPolicy: {{ .Values.storage.reclaimPolicy }}
{{- if eq .Values.global.provider "aws" }}
allowVolumeExpansion: {{ .Values.storage.allowVolumeExpansion }}
provisioner:  ebs.csi.aws.com
parameters:
  {{- with .Values.storage.parameters }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- else if eq .Values.global.provider "azure" }}
allowVolumeExpansion: {{ .Values.storage.allowVolumeExpansion }}
provisioner: disk.csi.azure.com
parameters:
  {{- with .Values.storage.parameters }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}

{{- else if eq .Values.global.provider "local" }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "ethnode-clc.fullname" . }}-{{ .Values.global.network }}-{{ .Values.global.env }}-storage
  namespace: {{ .Release.Namespace }}
  labels:
    type: local
spec:
  storageClassName: {{ include "ethnode-clc.fullname" . }}-{{ .Values.global.network }}-{{ .Values.global.env }}-storage
  capacity:
    storage: {{ .Values.storage.size | quote }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/{{ include "ethnode-clc.fullname" . }}-{{ .Values.global.network }}-{{ .Values.global.env }}-storage"

{{- end }}


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ethnode-clc.fullname" . }}-{{ .Values.global.network }}-{{ .Values.global.env }}-pvc
  labels:
    name: {{ include "ethnode-clc.fullname" . }}-{{ .Values.global.network }}-{{ .Values.global.env }}
    {{- if or (eq .Values.global.provider "aws") (eq .Values.global.provider "azure") }}
    {{ if .Values.global.snapshot.sot  -}}
    "schedule/{{ .Values.global.snapshot.schedule | replace "@" ""}}": "enabled"
    {{- end }}
    {{- include "ethnode-clc.labels" . | nindent 4 }}  
    {{- end }}
  namespace: {{ include "ethnode.namespace" . }}
spec: 
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ include "ethnode-clc.fullname" . }}-{{ .Values.global.network }}-{{ .Values.global.env }}-storage
  resources: 
    requests:
      storage: {{ .Values.storage.size | quote }}
  {{- if or (eq .Values.global.provider "aws") (eq .Values.global.provider "azure") -}}
  {{- if .Values.restore.enabled -}}
  dataSource:
    name: {{ .Values.restore.snapshot }}
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  {{- end }}
  {{- end }}



{{- if or (eq .Values.global.provider "aws") (eq .Values.global.provider "azure") }}

{{ if .Values.global.snapshot.sot  -}}

---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: {{ include "ethnode-clc.fullname" . }}-{{ .Values.global.network }}-{{ .Values.global.env }}-vsc
  labels:
    {{- include "ethnode-clc.labels" . | nindent 4 }}  
  namespace: {{ include "ethnode.namespace" . }}
deletionPolicy: Delete
{{- if eq .Values.global.provider "aws" }}
driver: ebs.csi.aws.com
parameters:
  tagSpecification_1: "name={{ include "ethnode-clc.fullname" . }}-{{ .Values.global.network }}-{{ .Values.global.env }}"
  tagSpecification_2: "network={{ .Values.global.network }}"
  tagSpecification_3: "clc=teku"
{{- else if eq .Values.global.provider "azure" }}
driver: disk.csi.azure.com
{{- end }}  
---


apiVersion: snapscheduler.backube/v1
kind: SnapshotSchedule
metadata:
  name:  {{ include "ethnode-clc.fullname" . }}-{{ .Values.global.network }}-{{ .Values.global.env }}-vss
  namespace: {{ include "ethnode.namespace" . }}
spec:
  claimSelector:
    matchLabels:
      name: {{ include "ethnode-clc.fullname" . }}-{{ .Values.global.network }}-{{ .Values.global.env }}
      "schedule/{{ .Values.global.snapshot.schedule | replace "@" ""}}": "enabled"
      {{- include "ethnode-clc.labels" . | nindent 6 }}      
  schedule: "{{ .Values.global.snapshot.schedule }}"
  retention:
    # retained specified in hours. (168h = 1 week)
    expires: "168h"
    maxCount: 10  # optional
  # set of labels can be added to each VolumeSnapshot object
  snapshotTemplate:
    labels:  
      name: {{ include "ethnode-clc.fullname" . }}-{{ .Values.global.network }}-{{ .Values.global.env }}
      {{- include "ethnode-clc.labels" . | nindent 6 }}  
    snapshotClassName: {{ include "ethnode-clc.fullname" . }}-{{ .Values.global.network }}-{{ .Values.global.env }}-vsc

{{- end }}

{{- end }}
