{{ if eq .Values.global.clc "teku" -}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ethnode-clc.fullname" . }}-{{ .Values.global.network }}-{{ .Values.global.env }}-config
  labels:
    {{- include "ethnode-clc.labels" . | nindent 4 }}
  namespace: {{ include "ethnode.namespace" . }}
data:

  log4j.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration status="INFO" monitorInterval="5">

      <Properties>
        <Property name="root.log.level">INFO</Property>
      </Properties>

      <Appenders>
        <Console name="Console" target="SYSTEM_OUT">
          <PatternLayout alwaysWriteExceptions="false" pattern='{"@timestamp":"%d{ISO8601}","level":"%level","thread":"%t","class":"%c{1}","message":"%replace{%msg}{[\p{Cntrl}&amp;&amp;[^\r\n]]}{}","throwable":"%enc{%throwable}{JSON}"}%n'/>
        </Console>
      </Appenders>

      <Loggers>
        <Root level="${sys:root.log.level}">
          <AppenderRef ref="Console" />
        </Root>
      </Loggers>

    </Configuration>

{{ end }}